DATA_LOADED = 'data_loaded'
START_PROCESSING = 'start_processing'
STOP_PROCESSING = 'stop_processing'
DATA_SAVED = 'data_saved'
SENSOR_DETECTED = 'sensor_detected'
SKIP_FLAG_DETECTED = 'skip_flag_detected'

DATA_LOADING_FAILED = 'data_loading_failed'
INVALID_INPUT_VALUE = 'invalid_input_value'
VALIDATION_FAILED = 'validation_failed'
